name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Install trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'

    - name: Cache wasm-bindgen-cli
      id: cache-wasm-bindgen
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/wasm-bindgen
        key: wasm-bindgen-${{ runner.os }}

    - name: Install wasm-bindgen-cli
      if: steps.cache-wasm-bindgen.outputs.cache-hit != 'true'
      run: cargo install wasm-bindgen-cli

    - name: Test backend
      run: cargo test

    - name: Auto format code
      run: cargo fmt --all

    - name: Run clippy (allow warnings)
      run: cargo clippy --all-targets --all-features

    - name: Build frontend
      run: |
        cd frontend
        trunk build --release

    - name: Build backend
      run: cargo build --release

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Check if deploy hook is configured
      run: |
        if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
          echo "⚠️ RENDER_DEPLOY_HOOK secret not configured"
          echo "Please add it in GitHub repository settings: Settings → Secrets and variables → Actions"
          echo "Get the deploy hook URL from your Render service settings"
          exit 1
        fi
        
    - name: Trigger Render deployment
      run: |
        echo "🚀 Triggering deployment to Render..."
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}" \
          -H "Content-Type: application/json" \
          -d '{"ref": "${{ github.sha }}"}'
        echo "✅ Deploy hook triggered successfully"
