name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install Trunk
      run: |
        wget -qO- https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        sudo mv trunk /usr/local/bin/

    - name: Install wasm-bindgen-cli
      run: cargo install wasm-bindgen-cli

    - name: Test backend
      run: cargo test

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build frontend
      run: |
        cd frontend
        trunk build --release

    - name: Build backend
      run: cargo build --release

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Render deployment
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      # Note: need to add RENDER_DEPLOY_HOOK secret in GitHub repository settings
